# Generated by Django 3.1.6 on 2021-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORPWD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bayad',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='itemvariant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='costumer_address',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='itemwiths',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='sender_address',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_variations',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='variants',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variants',
            name='item',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Cnum',
            new_name='ContactNumber',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='date',
            new_name='DateUpdated',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='address',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='Idpic',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='age',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='Avatar',
            field=models.FileField(default='default.jpeg', upload_to='avatar'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='BAYAD',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='ItemVariant',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
